### ISSUE TITLE
error while setting up the repo locally

### ISSUE THREAD

**Issue by 0saurabh0** [unicode-org/lstm_word_segmentation#27]
getting the error  
```
File "/home/srvk/Desktop/lstm_w/lstm_word_segmentation/lstm_word_segmentation/word_segmenter.py", line 4, in <module>
    from icu import Char
ImportError: cannot import name 'Char' from 'icu' (/home/srvk/Desktop/lstm_w/lsvenv/lib/python3.11/site-packages/icu/__init__.py)
```
while setting up the project locally, even though `icu` is already installed in the system
Python version -  3.11.7
OS - Archlinux

Also, 
#### Improving Project Setup and Documentation for Better Developer Experience
for someone who is a new contributor to the project like myself, have encountered challenges with the setup process. The lack of a defined project structure and clear setup instructions has made it difficult to get started and contribute effectively. 

it would be better if we: 

- define the setup instructions, including steps for installing dependencies and running scripts in the README
- maybe add a requirements.txt file to list all project dependencies, facilitating easy installation with a single command (pip install -r requirements.txt).
- Provide examples or templates for setting up the project locally, including any necessary environment variables or configuration options.

which will:

- Improves the onboarding experience for new contributors by providing clear guidance on project setup.
- Streamlines the dependency installation process, reducing the time spent troubleshooting and installing the modules individually.

**Comment by sffc** [comment]
Can you verify that package `icu` is fully installed and working as expected? Please find installation instructions here:

https://pypi.org/project/PyICU/

Note that installing the package from `pip` is not usually sufficient; you need to make sure that `libicu` is also installed on your system.

**Comment by 0saurabh0** [comment]
yes, I have already successfully installed `icu` which I found [here](https://pypi.org/project/PyICU/), but there is also this another `icu`  [package](https://pypi.org/project/icu/).
Do we need both?

Regarding the `libicu`, there are multiple different resources available on the web, can you please point me to some specific resourses?
 Also Is this `libicu` OS related? if yes, [this](https://archlinux.org/packages/core/x86_64/icu/) also is already installed, but the error still persists.

**Comment by 0saurabh0** [comment]
update: I've fixed the error.

let me know if, I should raise a PR for this


> #### Improving Project Setup and Documentation for Better Developer Experience

**Comment by 0saurabh0** [comment]
closing for now
